### ISSUE TITLE
Ability to add an aggregated calendar to another aggregated calendar

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/calendar-aggregator#8]
It would be nice to be able to add an aggregated calendar to another aggregated calendar. This would allow defining groups in one place. 

For example, the Boards and Commissions aggregated calendar contains 30+ separate calendars. Ideally those will not need to be added and managed individually on the higher level "Government" calendar.

**Comment by inghamn** [comment]
This is supposed to be possible.  There's just a bug in the code causing it to not sync.

**Comment by inghamn** [comment]
Synchronize is only working for direct aggregatedCalendars of aggregations.  (child calendars, but not grand children or further).

GoogleGateway::attendAllEvents() creates a patch for the event.  However, it is committing the patch against the child calendar.  Since the event (which is actually from a grandchild or further descendant calendar) is not actually from the child calendar, the attending patch does not do anything.

We need to figure out a way to determine the actual calendar_id for any arbitrary event - irrespective of what calendar we used to summon the event listing for.
